logging:
  file:
    path: /data/back-log
    max-size: 50MB
    max-history: 14
  level:
    root: warn
    org.hibernate.SQL: warn
spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/wonbae
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  port: 8080
