spring:
  profiles:
    active: dev

# logging:
#   level:
#     jdbc: INFO
#     com.thoughtlib.springbatchpractice: INFO
#     org.hibernate.SQL: INFO
#     org.hibernate.type: INFO
#   file:
#     path: /tmp